# 예외처리

### 예외란?

프로그램을 만든 프로그래머가 상정한 정상적인 처리에서 벗어나는 경우에 이를 처리하기 위한 방법이다.

### 예외처리가 없을 경우의 에러 발생 코드

```jsx
package exception;

class Calculator{
    int left, right;
    public void setOprands(int left, int right){
        this.left = left;
        this.right = right;
    }
    public void divide(){
        System.out.print("계산결과는 ");
        System.out.print(this.left/this.right);
        System.out.print(" 입니다.");
    }
} 
public class CalculatorDemo {
    public static void main(String[] args) {
        Calculator c1 = new Calculator();
        c1.setOprands(10, 0);
        c1.divide();
    }
}
```

- 에러 내용
    
    ```jsx
    Exception in thread "main" 계산결과는 java.lang.ArithmeticException: / by zero
    	at exception.Calculator.divide(CalculatorDemo.java:11)
    	at exception.CalculatorDemo.main(CalculatorDemo.java:19)
    ```
    
    - ‘계산결과는’이 출력되었다는 의미는 9행은 실행되었음
    - 10을 0으로 나누려고 해서 발생한 Error이다.
    
    ### 예외처리를 해서 정상적으로 작동 되게 하는 코드
    
    ```jsx
    package exception;
    
    class Calculator{
        int left, right;
        public void setOprands(int left, int right){
            this.left = left;
            this.right = right;
        }
        
        //아래의 코드로 작성하면 에러 발생 => 10을 0으로 나눠서
    //    public void divide(){
    //        System.out.print("계산결과는 ");
    //        System.out.print(this.left/this.right);
    //        System.out.print(" 입니다.");
    //    }
        
        //예외처리를 해서 정상적으로 작동 되게 하는 법
        public void divide(){
            try {
                System.out.print("계산결과는 ");
                System.out.print(this.left/this.right);
                System.out.print(" 입니다.");
            } catch(Exception e){
                System.out.println("오류가 발생했습니다 : "+e.getMessage());
            }
        }
    } 
    public class CalculatorDemo {
        public static void main(String[] args) {
            Calculator c1 = new Calculator();
            c1.setOprands(10, 0);
            c1.divide();
        }
    }
    ```